#!/bin/bash
# Guide to get connection string from Supabase Dashboard
# Since password isn't accessible via API, this provides step-by-step instructions

echo "🔍 How to Get Database Connection String from Supabase Dashboard"
echo "=================================================================="
echo ""
echo "The database password is not accessible via API for security reasons."
echo "You need to get it from the Supabase dashboard."
echo ""
echo "📋 Step-by-Step Instructions:"
echo ""
echo "1. Open Supabase Dashboard:"
echo "   https://supabase.com/dashboard/project/kwhnrlzibgfedtxpkbgb/settings/database"
echo ""
echo "2. Find 'Connection string' section:"
echo "   - Scroll down on the Database settings page"
echo "   - Look for a section titled 'Connection string' or 'Connection parameters'"
echo "   - OR look for 'Connection pooling' section"
echo ""
echo "3. Select 'URI' tab:"
echo "   - You may see tabs: 'URI', 'JDBC', 'Connection pooling', etc."
echo "   - Click on 'URI' tab"
echo "   - If you don't see tabs, look for a dropdown or button to switch views"
echo ""
echo "4. Alternative locations to check:"
echo "   - Settings → Database → Connection string"
echo "   - Settings → Database → Connection pooling → URI"
echo "   - Project Settings → Database → Connection info"
echo ""
echo "5. Copy the connection string:"
echo "   It should look like:"
echo "   postgresql://postgres.kwhnrlzibgfedtxpkbgb:[PASSWORD]@db.kwhnrlzibgfedtxpkbgb.supabase.co:5432/postgres"
echo ""
echo "6. If you can't find the connection string:"
echo "   - Look for 'Database password' section"
echo "   - You may need to reset the password"
echo "   - Then construct the connection string manually:"
echo "     postgresql://postgres.kwhnrlzibgfedtxpkbgb:[NEW_PASSWORD]@db.kwhnrlzibgfedtxpkbgb.supabase.co:5432/postgres"
echo ""
echo "📝 Quick Reference:"
echo "   Database Host: db.kwhnrlzibgfedtxpkbgb.supabase.co"
echo "   Port: 5432 (direct connection - NOT 6543)"
echo "   Database: postgres"
echo "   User: postgres.kwhnrlzibgfedtxpkbgb"
echo ""
echo "🔗 Direct Link:"
echo "   https://supabase.com/dashboard/project/kwhnrlzibgfedtxpkbgb/settings/database"
echo ""

